#!/usr/bin/env python3
"""
Regenerate battery_icons.h for the InkTime ESP32 frame.

Produces 11 icons (0..100%, step 10) at 24x24, 1 byte/pixel, 4-color
palette (0=black, 1=white, 2=red, 3=yellow).

Design (24x24):
- Battery body: x=2..21 (20 wide), y=6..17 (12 tall)
- Terminal nub on the right: x=22..23, y=10..13
- Outline: top/bottom bars x=2..21 at y=6,17; side walls x=2,x=21 at y=7..16
- Fill: starts 1px inside the body (x=3..20), spans the level percentage
- Low battery (<20%): fill drawn in RED (idx 2) so it's visible/warning
- The overlay code paints the icon area white first, so we only need
  non-white pixels in the arrays (transparent = white = 1)
"""
from __future__ import annotations

import argparse
from pathlib import Path

W = H = 24
PALETTE = {0: "black", 1: "white", 2: "red", 3: "yellow"}

# Battery body geometry
BODY_X0 = 2
BODY_X1 = 21  # inclusive
BODY_Y0 = 6
BODY_Y1 = 17  # inclusive
NUB_X0 = 22
NUB_X1 = 23
NUB_Y0 = 10
NUB_Y1 = 13

# Fill area (inside body, 1px inset)
FILL_X0 = 3
FILL_X1 = 20  # inclusive -> 18 wide
FILL_Y0 = 7
FILL_Y1 = 16  # inclusive -> 10 tall


def make_icon(level_pct: int) -> list[list[int]]:
    """Return a 24x24 grid of palette indices for the given battery level."""
    grid = [[1] * W for _ in range(H)]  # all white/transparent

    # Outline
    for x in range(BODY_X0, BODY_X1 + 1):
        grid[BODY_Y0][x] = 0
        grid[BODY_Y1][x] = 0
    for y in range(BODY_Y0 + 1, BODY_Y1):
        grid[y][BODY_X0] = 0
        grid[y][BODY_X1] = 0
    # Nub
    for x in range(NUB_X0, NUB_X1 + 1):
        for y in range(NUB_Y0, NUB_Y1 + 1):
            grid[y][x] = 0

    # Fill
    fill_w = FILL_X1 - FILL_X0 + 1  # 18
    fill_h = FILL_Y1 - FILL_Y0 + 1  # 10
    n_filled = round(fill_w * fill_h * level_pct / 100.0)
    n_filled = max(0, min(fill_w * fill_h, n_filled))

    # Low-battery warning color when < 20%
    fill_color = 2 if level_pct < 20 else 0  # red for 0%/10%, black otherwise

    # Fill left-to-right, top-to-bottom (visual: level fills from left)
    count = 0
    for y in range(FILL_Y0, FILL_Y1 + 1):
        for x in range(FILL_X0, FILL_X1 + 1):
            if count >= n_filled:
                break
            grid[y][x] = fill_color
            count += 1

    return grid


def grid_to_c_array(grid: list[list[int]]) -> str:
    lines = []
    for y in range(H):
        row = ", ".join(f"0x{grid[y][x]:02X}" for x in range(W))
        lines.append("  " + row + ",")
    return "\n".join(lines)


def generate_header() -> str:
    out = []
    out.append("// Auto-generated by tools/make_battery_icons.py")
    out.append("// 11 battery icons (0..100 step 10) 24x24, 1 byte/pixel (0=B,1=W,2=R,3=Y)")
    out.append("#ifndef BATTERY_ICONS_H")
    out.append("#define BATTERY_ICONS_H")
    out.append("")
    out.append("#include <Arduino.h>")
    out.append("")
    out.append("#define BATTERY_ICON_W 24")
    out.append("#define BATTERY_ICON_H 24")
    out.append("#define BATTERY_ICON_LEN (BATTERY_ICON_W * BATTERY_ICON_H)  // 576")
    out.append("#define BATTERY_LEVEL_COUNT 11")
    out.append("")
    out.append("// Icon position on 480x800 canvas (matches render_daily_photo.py):")
    out.append("#define BATTERY_ICON_X 440        // 16px from right edge")
    out.append("#define BATTERY_ICON_Y 716        // 16px below the photo area (text area top + 16)")
    out.append("")
    for pct in range(0, 101, 10):
        grid = make_icon(pct)
        arr = grid_to_c_array(grid)
        out.append(f"static const uint8_t battery_icon_{pct:03d}[BATTERY_ICON_LEN] PROGMEM = {{")
        out.append(arr)
        out.append("};")
        out.append("")
    out.append("// level_to_index: 0..100 -> 0..10 (rounded down to nearest 10)")
    out.append("static inline uint8_t battery_level_to_index(uint8_t pct) {")
    out.append("  if (pct >= 100) return 10;")
    out.append("  if (pct < 10) return 0;")
    out.append("  return (uint8_t)(pct / 10);")
    out.append("}")
    out.append("")
    out.append("// Lookup the icon for a given level (0..100).")
    out.append("static inline const uint8_t* battery_icon_for_level(uint8_t pct) {")
    out.append("  static const uint8_t* const LUT[11] = {")
    for i in range(11):
        suffix = "," if i < 10 else ""
        out.append(f"    battery_icon_{i*10:03d},  // {i*10}%{suffix}")
    out.append("  };")
    out.append("  return LUT[battery_level_to_index(pct)];")
    out.append("}")
    out.append("")
    out.append("#endif // BATTERY_ICONS_H")
    out.append("")
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate battery_icons.h")
    parser.add_argument("--out", type=Path, default=Path("battery_icons.h"))
    args = parser.parse_args()
    args.out.write_text(generate_header(), encoding="utf-8")
    # Sanity self-check
    for pct in range(0, 101, 10):
        grid = make_icon(pct)
        assert len(grid) == H and all(len(r) == W for r in grid), "bad dims"
        assert all(v in PALETTE for row in grid for v in row), "bad palette idx"
    print(f"Wrote {args.out} ({len(generate_header())} bytes, 11 icons 24x24)")


if __name__ == "__main__":
    main()
